
language: python

python:
  - "3.6"

services:
  - docker

env:
  global:
    - AVALON_MONGO=mongodb://localhost:27017
    - PATHEXT=.SH  # This is a workaround
    - CONFIG_ROOT=$PWD
    - DCC_WORKDIR=/workspace
    - DCC_DOCKERS=$PWD/tests/bin
    - PYBLISH_BASE=$PWD/pyblish-base
    - PYBLISH_QML=$PWD/pyblish-qml
    - AVALON_CORE=$PWD/core
    - AVALON_LAUNCHER=$PWD/launcher
    - AVALON_SETUP=$PWD/setup
    - PYTHONPATH="$PYBLISH_BASE:\
                  $PYBLISH_QML:\
                  $AVALON_CORE:\
                  $AVALON_LAUNCHER:\
                  $AVALON_SETUP:\
                  $CONFIG_ROOT"
  matrix:
    - MAYA_VERSION=2018
    - MAYA_VERSION=2017
    - MAYA_VERSION=2016sp1

before_install:
  - git clone https://github.com/getavalon/core.git
  - git clone https://github.com/getavalon/setup.git
  - git clone https://github.com/getavalon/launcher.git
  - git clone https://github.com/pyblish/pyblish-base.git
  - git clone https://github.com/pyblish/pyblish-qml.git
  - pip install tox coveralls

install:
  - docker run --name avalon-mongo -p 27017:27017 -d mongo
  - docker run --rm --name maya
    --link avalon-mongo:mongo
    -e AVALON_MONGO=mongodb://mongo:27017
    -v $(pwd):$DCC_WORKDIR --workdir=$DCC_WORKDIR
    -d -i -t mottosso/maya:${MAYA_VERSION} /bin/bash

before_script:
  - chmod +x tests/bin/mayapy.sh

script:
  - tox

after_success:
  - coveralls

sudo: required
dist: trusty
