
language: python

python:
  - "2.7"
  - "3.6"

matrix:
  include:
  - env:
    - MAYA_VERSION=2018
  - env:
    - MAYA_VERSION=2017
  - env:
    - MAYA_VERSION=2016sp1

services:
  - docker

before_install:
  - git clone https://github.com/getavalon/core.git
  - git clone https://github.com/getavalon/setup.git
  - git clone https://github.com/getavalon/launcher.git
  - git clone https://github.com/pyblish/pyblish-base.git
  - git clone https://github.com/pyblish/pyblish-qml.git

install:
  - pip install tox-travis coveralls
  - docker run --name avalon-mongo -d mongo
  - docker run --rm --name maya
    -v $(pwd):/workspace --workdir=/workspace
    --link avalon-mongo:mongo
    -d -i -t mottosso/maya:${MAYA_VERSION} /bin/bash

env:
  global:
    - AVALON_MONGO=mongodb://mongo:27017
    - PYBLISH_BASE=$(pwd)/pyblish-base
    - PYBLISH_QML=$(pwd)/pyblish-qml
    - AVALON_CORE=$(pwd)/core
    - AVALON_LAUNCHER=$(pwd)/launcher
    - AVALON_SETUP=$(pwd)/setup
    - CONFIG_ROOT=$(pwd)
    - PYTHONPATH=$PYBLISH_BASE:$PYBLISH_QML:$AVALON_CORE:$AVALON_LAUNCHER:$AVALON_SETUP:$CONFIG_ROOT
    - PATH=$(pwd)/tests/bin:$PATH

script:
  - tox

after_script:
  - pkill mongod

after_success:
  - coveralls

sudo: required
dist: trusty
