
language: python

python:
  - "3.6"

services:
  - docker

env:
  global:
    - PATHEXT=.SH  # This is a workaround
    - HOST_APPEXEC=$PWD/tests/bin
    - HOST_WORKDIR=$PWD
    - DOCKER_WORKDIR=/workspace
    - PYBLISH_BASE=$PWD/pyblish-base
    - PYBLISH_QML=$PWD/pyblish-qml
    - AVALON_CORE=$PWD/core
    - AVALON_LAUNCHER=$PWD/launcher
    - AVALON_SETUP=$PWD/setup
    - AVALON_SFTPC=$PWD/avalon-sftpc
    - PYTHONPATH=$PYTHONPATH:$PYBLISH_BASE
    - PYTHONPATH=$PYTHONPATH:$PYBLISH_QML
    - PYTHONPATH=$PYTHONPATH:$AVALON_CORE
    - PYTHONPATH=$PYTHONPATH:$AVALON_LAUNCHER
    - PYTHONPATH=$PYTHONPATH:$AVALON_SETUP
    - PYTHONPATH=$PYTHONPATH:$AVALON_SFTPC
    - PYTHONPATH=$PYTHONPATH:$PWD
    - AVALON_MONGO=mongodb://localhost:27017
    - AVALON_DB=avalon:test
    - AVALON_CONFIG=reveries
  matrix:
    - MAYA_VERSION=2018
    - MAYA_VERSION=2017
    - MAYA_VERSION=2016sp1

before_install:
  - git clone https://github.com/getavalon/core.git
  - git clone https://github.com/getavalon/setup.git
  - git clone https://github.com/getavalon/launcher.git
  - git clone https://github.com/pyblish/pyblish-base.git
  - git clone https://github.com/pyblish/pyblish-qml.git
  - git clone https://github.com/davidlatwe/avalon-sftpc.git
  - pip install tox coveralls

install:
  - docker run --name avalon-mongo -p 27017:27017 -d mongo
  - docker run --rm --name maya
    --link avalon-mongo:mongo
    -e AVALON_MONGO=mongodb://mongo:27017
    -v $(pwd):$DOCKER_WORKDIR --workdir=$DOCKER_WORKDIR
    -d -i -t mottosso/maya:${MAYA_VERSION} /bin/bash

before_script:
  - chmod +x tests/bin/mayapy.sh

script:
  - tox

after_success:
  - coveralls

sudo: required
dist: trusty
