schema = "avalon-core:config-1.0"

[[apps]]
name = "maya2018"
label = "Maya 2018"

[[tasks]]
name = "model"

[[tasks]]
name = "render"

[[tasks]]
name = "animate"

[[tasks]]
name = "rig"

[[tasks]]
name = "lookdev"

[[tasks]]
name = "layout"

[template]
work = "{root}/{project}/Avalon/{silo}/{asset}/work/{task}/{user}/{app}"
publish = "{root}/{project}/Avalon/{silo}/{asset}/publish/{subset}/v{version:0>3}/{representation}"


[[families]]
name = "reveries.model"
label = "Model"
icon = "cubes"

[[families]]
name = "reveries.rig"
label = "Rig"
icon = "sitemap"

[[families]]
name = "reveries.look"
label = "Look"
icon = "paint-brush"

[[families]]
name = "reveries.setdress"
label = "Set Dress"
icon = "tree"

[[families]]
name = "reveries.animation"
label = "Animation"
icon = "male"

[[families]]
name = "reveries.pointcache"
label = "PointCache"
icon = "diamond"

[[families]]
name = "reveries.camera"
label = "Camera"
icon = "video-camera"

[[families]]
name = "reveries.mayaShare"
label = "MayaShare(.ma)"
icon = "share-square-o"
