schema = "avalon-core:config-1.0"
[[apps]]
name = "shell"
label = "Shell"

[[apps]]
name = "maya2016"
label = "Autodesk Maya 2016"

[[apps]]
name = "mayapy2016"
label = "Autodesk Maya 2016 (Standalone)"

[[apps]]
name = "maya2017"
label = "Autodesk Maya 2017"

[[apps]]
name = "mayapy2017"
label = "Autodesk Maya 2017 (Standalone)"

[[apps]]
name = "maya2018"
label = "Autodesk Maya 2018"

[[apps]]
name = "mayapy2018"
label = "Autodesk Maya 2018 (Standalone)"

[[tasks]]
name = "model"

[[tasks]]
name = "animate"

[[tasks]]
name = "rig"

[[tasks]]
name = "lookdev"

[[tasks]]
name = "layout"

[template]
work = "{root}/{project}/Maya/Avalon/{silo}/{asset}/work/{task}"
publish = "{root}/{project}/Maya/Avalon/{silo}/{asset}/publish/{subset}/v{version:0>3}/{representation}"
