schema = "avalon-core:config-1.0"

[[apps]]
name = "maya2018"
label = "Maya 2018"

[[tasks]]
name = "modeling"

[[tasks]]
name = "rigging"

[[tasks]]
name = "lookdev"

[[tasks]]
name = "charFX"

[[tasks]]
name = "setdressing"

[[tasks]]
name = "animating"

[[tasks]]
name = "layout"

[[tasks]]
name = "lighting"

[template]
work = "{root}/{project}/Avalon/{silo}/{asset}/work/{task}/{user}/{app}"
publish = "{root}/{project}/Avalon/{silo}/{asset}/publish/{subset}/v{version:0>3}/{representation}"


# Family name should be lower case

[[families]]
name = "reveries.shotpkg"
label = "Shot Package"
icon = "shopping-basket"

[[families]]
name = "reveries.imgseq"
label = "Image Sequence"
icon = "film"

[[families]]
name = "reveries.model"
label = "Model"
icon = "cubes"

[[families]]
name = "reveries.xgen"
label = "XGen"
icon = "paw"

[[families]]
name = "reveries.rig"
label = "Rig"
icon = "sitemap"

[[families]]
name = "reveries.look"
label = "Look"
icon = "paint-brush"

[[families]]
name = "reveries.texture"
label = "Texture"
icon = "picture-o"

[[families]]
name = "reveries.setdress"
label = "Set Dress"
icon = "tree"

[[families]]
name = "reveries.animation"
label = "Animation"
icon = "male"

[[families]]
name = "reveries.pointcache"
label = "PointCache"
icon = "diamond"

[[families]]
name = "reveries.camera"
label = "Camera"
icon = "video-camera"

[[families]]
name = "reveries.lightset"
label = "Light Set"
icon = "lightbulb-o"

[[families]]
name = "reveries.standin"
label = "Arnold Stand-In"
icon = "coffee"

[[families]]
name = "reveries.mayashare"
label = "Maya Share (.ma)"
icon = "share-square-o"
