schema = "avalon-core:inventory-1.0"


# project settings

resolution_width = 1920
resolution_height = 1080
fps = 30
handles = 1
edit_in = 101
edit_out = 200

[pipeline]
[pipeline.maya]
animation_cache = "Alembic"

[deadline]
[deadline.job]
maya_cache_pool = "1---less_than_15minutes"
maya_cache_group = "maya2017vray36"
maya_cache_priority = 95
maya_render_pool = "1---less_than_15minutes"
maya_render_group = "maya2017vray36"
maya_render_priority = 60


# asset settings

[[assets]]
label = "Dummy"
name = "Dummy"
tasks = [ "lookdev", "model", "rig",]


# shot settings

[[shots]]
label = "Example"
tasks = [ "animate", "layout",]
name = "Example"
edit_in = 101
edit_out = 122

