schema = "avalon-core:inventory-1.0"


# project settings

resolution_width = 1920
resolution_height = 1080
fps = 30
handles = 1
edit_in = 101
edit_out = 200

[role]
admin = [
]

[pipeline]
[pipeline.maya]
turntable = "LookDevStage"
# Whether to use `all` lights or `default` light in playblast
playblastLights = "default"
pointcache = [
    "Alembic",
    "GPUCache",
    "FBXCache",
]  # This also determined the preferable cache format by order.

[deadline]
publishUser = "avalon"

[deadline.maya]
pool = [
	"1---less_than_15minutes",
	"2---about_30minutes",
	"3---about_90minutes",
	"4---more_than_120minutes",
]
group = [
	"maya2017vray36",
	"maya2018_2",
]

[deadline.maya.priorities]
pointcache = 95
render = 70
playblast = 95
